# Generated by Django 4.0.5 on 2022-07-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='board',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bond.coupontype'),
        ),
    ]
