# Generated by Django 4.0.5 on 2022-07-12 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0002_bond_board_alter_coupon_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='board',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='collateral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.coupon'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.currency'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='current_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='emitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.emitter'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='is_subordinated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='is_traded_in_TI',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='issue_volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='moex_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='placement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bond',
            name='yield_to_maturity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
