# Generated by Django 4.0.5 on 2022-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0003_alter_bond_board_alter_bond_collateral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='facevalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='start_facevalue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
