# Generated by Django 4.0.5 on 2022-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0006_emitter_updated_by_alter_emitter_moex_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emitter',
            options={'ordering': ['updated_by', '-revenue']},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.coupontype'),
        ),
    ]
