# Generated by Django 4.0.5 on 2022-09-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0009_bond_liquidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
