# Generated by Django 4.0.5 on 2022-10-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0010_bond_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_margin', models.FloatField(default=15)),
                ('operation_margin', models.FloatField(default=18)),
                ('roa', models.FloatField(default=10)),
                ('roe', models.FloatField(default=15)),
                ('nd_to_ebitda', models.FloatField(default=3)),
                ('interest_ratio', models.FloatField(default=33)),
                ('equity_level', models.FloatField(default=16)),
                ('cur_liquidity', models.FloatField(default=150)),
                ('fast_liquidity', models.FloatField(default=100)),
                ('absolute_liquidity', models.FloatField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='normal_values',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bond.normalvalues'),
        ),
    ]
