# Generated by Django 4.0.5 on 2022-10-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0012_rename_absolute_liquidity_normalvalues_absolute_liquidity1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalvalues',
            name='nd_to_equity1',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='normalvalues',
            name='nd_to_equity2',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='nd_to_ebitda1',
            field=models.FloatField(default=2),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='nd_to_ebitda2',
            field=models.FloatField(default=4),
        ),
    ]
