# Generated by Django 4.0.5 on 2022-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0013_normalvalues_nd_to_equity1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalvalues',
            name='title',
            field=models.CharField(default='все', max_length=50),
        ),
    ]
