# Generated by Django 4.0.5 on 2023-03-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0015_remove_industry_normal_values_emitter_normal_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalvalues',
            name='absolute_liquidity1',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='absolute_liquidity2',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='cur_liquidity1',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='cur_liquidity2',
            field=models.FloatField(default=0.75),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='fast_liquidity1',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='fast_liquidity2',
            field=models.FloatField(default=0.5),
        ),
        migrations.CreateModel(
            name='FinIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=4)),
                ('type', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('value', models.BigIntegerField()),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.bond')),
            ],
        ),
    ]
