# Generated by Django 4.0.5 on 2023-04-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0016_alter_normalvalues_absolute_liquidity1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finindicator',
            name='bond',
        ),
        migrations.AddField(
            model_name='finindicator',
            name='emitter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bond.emitter'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReportLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('hash', models.IntegerField(blank=True, null=True)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.emitter')),
            ],
        ),
    ]
