# Generated by Django 4.0.5 on 2023-04-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0017_remove_finindicator_bond_finindicator_emitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='e_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
