# Generated by Django 4.0.5 on 2023-04-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0018_emitter_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='ls_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
