# Generated by Django 4.0.5 on 2023-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0019_emitter_ls_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='okpo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
