# Generated by Django 4.0.5 on 2023-04-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0020_emitter_okpo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emitter',
            name='ls_id',
        ),
        migrations.AddField(
            model_name='emitter',
            name='ls_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
