# Generated by Django 4.0.5 on 2023-04-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0021_remove_emitter_ls_id_emitter_ls_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bond.industry'),
        ),
    ]
