# Generated by Django 4.0.5 on 2023-04-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0022_alter_sector_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finindicator',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='emitter',
            name='need_add_fin_data',
            field=models.BooleanField(default=False),
        ),
    ]
