# Generated by Django 4.0.5 on 2023-05-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0024_creditrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrating',
            name='agency',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='creditrating',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditrating',
            name='value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
