# Generated by Django 4.0.5 on 2023-05-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0025_creditrating_agency_alter_creditrating_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
