# Generated by Django 4.0.5 on 2023-05-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0026_paymenttype_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
