# Generated by Django 4.0.5 on 2023-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0027_bond_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrating',
            name='value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
