# Generated by Django 4.0.5 on 2023-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0028_alter_creditrating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
