# Generated by Django 4.0.5 on 2023-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0030_sector_risk_level_alter_sector_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='inn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
