# Generated by Django 4.0.5 on 2023-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0031_emitter_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='report_data_level',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
