# Generated by Django 4.0.5 on 2023-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0033_emitter_is_report_ok'),
    ]

    operations = [
        migrations.AddField(
            model_name='emitter',
            name='ifrs_exists',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
