# Generated by Django 4.2.3 on 2023-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0036_medianvalues_report_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedianValues',
            new_name='MedianValue',
        ),
    ]
