# Generated by Django 4.2.3 on 2025-01-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0041_alter_bond_liquidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ST', 'Start'), ('DW', 'Downloaded'), ('UZ', 'Unzipped'), ('IM', 'Imaged'), ('PR', 'Parsed')], default='ST', max_length=2)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('reporting_period', models.CharField(blank=True, max_length=8, null=True)),
                ('file_path', models.CharField(blank=True, max_length=200, null=True)),
                ('images_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('emitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bond.emitter')),
            ],
        ),
    ]
