# Generated by Django 4.2.3 on 2025-01-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0042_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(default='rsbu', max_length=4),
        ),
    ]
