# Generated by Django 4.2.3 on 2025-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0043_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
