# Generated by Django 4.2.3 on 2025-01-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond', '0044_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='unit_of_measurement',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('ST', 'Start'), ('DW', 'Downloaded'), ('UZ', 'Unzipped'), ('IM', 'Imaged'), ('PR', 'Parsed'), ('ER', 'Error')], default='ST', max_length=2),
        ),
    ]
